from pydantic import BaseModel, Field
from typing import List, Optional

class StartInterviewRequest(BaseModel):
    candidate_name: str = Field(..., description="Name of the candidate")
    role: str = Field(..., description="Applied role description")
    resume: str = Field(..., description="Text content of the candidate's resume")
    candidate_id: Optional[str] = Field(None, description="Optional candidate ID link")


class StartInterviewResponse(BaseModel):
    session_id: str = Field(..., description="Unique ID for the interview session")
    first_question: str = Field(..., description="The first interview question generated by Gemini")

class GenerateQuestionRequest(BaseModel):
    session_id: str = Field(..., description="Unique ID for the interview session")

class GenerateQuestionResponse(BaseModel):
    question_number: int = Field(..., description="Current question index (1-based)")
    question: str = Field(..., description="The generated interview question")

class EvaluateAnswerRequest(BaseModel):
    question: str = Field(..., description="The question that was asked")
    answer: str = Field(..., description="The candidate's transcribed answer")
    role: str = Field(..., description="The role applied for")
    resume: str = Field(..., description="The candidate's resume content")
    session_id: Optional[str] = Field(None, description="Optional session ID to persist details")

class EvaluateAnswerResponse(BaseModel):
    technical_score: int = Field(..., ge=0, le=10, description="Technical correctness and correctness score")
    communication_score: int = Field(..., ge=0, le=10, description="Articulation, structural clarity and delivery score")
    confidence_score: int = Field(..., ge=0, le=10, description="Confidence, assurance and flow score")
    problem_solving_score: int = Field(..., ge=0, le=10, description="Logical reasoning and analytical processing score")
    relevance_score: int = Field(..., ge=0, le=10, description="Relevance and direct answering score")
    completeness_score: int = Field(..., ge=0, le=10, description="Completeness and detail coverage score")
    feedback: str = Field(..., description="Constructive qualitative feedback on the answer")


class NextQuestionRequest(BaseModel):
    session_id: str = Field(..., description="Unique ID for the interview session")

class NextQuestionResponse(BaseModel):
    question_number: int = Field(..., description="Next question number (1-based)")
    next_question: str = Field(..., description="The generated next question")
    is_finished: bool = Field(False, description="Flag indicating if the interview has reached the question limit")

class EndInterviewRequest(BaseModel):
    session_id: str = Field(..., description="Unique ID for the interview session")

class EndInterviewResponse(BaseModel):
    overall_score: float = Field(..., description="Overall calculated score (average or weighted)")
    summary: str = Field(..., description="Comprehensive summary of candidate performance")
    recommendation: str = Field(..., description="Recommendation status: 'Selected', 'Hold', or 'Rejected'")
